apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: demo-trioapp-2
spec:
  promotionFlows:
    - name: flow2
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - merge
  promotionTemplate:
    versionSource:
      file: version.yaml
      jsonPath: $.version
    promotion:
      version.yaml:
        jsonPaths:
          - $.version
  concurrency: terminate
