apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: test
spec:
  moshe: ziv
  promotionFlows:
    - name: flow2
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - hey
  concurrency: queue
