apiVersion: codefresh.io/v1beta2
kind: Product242
metadata:
  name: test
spec:
  promotionFlows:
    - name: flow2
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values: []

  concurrency: terminate