apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: flow2
  annotations:
    description: ""
spec:
  triggerEnvironment: staging
  steps:
    - environment: prod
      dependsOn:
        - staging
      policy:
        action: commit
  postTrigger: promotion1
